[book]
authors = ["Cmesen111"]
language = "zh-CN"
multilingual = true
src = "src"
title = "Aptos Move 语言圣经"

[output.html]
additional-css = ["src/theme/theme.css"]
additional-js = ["src/theme/giscus.js"]

[output.html.fold]
enable = true

[output.html.search]
enable = true